# netlify.toml

[build]
  # Directorio que Netlify publicará.
  # Aquí deben estar tus archivos estáticos (CSS, JS, imágenes).
  publish = "public"

[functions]
  # Directorio donde se encuentran tus funciones sin servidor.
  directory = "netlify/functions"

[[redirects]]
  # Esta es la regla clave:
  # Redirige TODAS las peticiones (/*) a nuestra función de PHP.
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200 # Status 200 significa "reescribir" la URL sin cambiarla en el navegador.# netlify.toml

[build]
  # This should be the folder with your index.php and assets (CSS, JS)
  publish = "public"

[functions]
  # This should point to where your serverless functions are
  directory = "netlify/functions"

[[redirects]]
  # Redirects ALL traffic from the root...
  from = "/*"
  # ...to your PHP handler function.
  to = "/.netlify/functions/api"
  # This is crucial! Status 200 means "rewrite" the path,
  # not "redirect" (which would change the URL in the browser).
  status = 200