# nixpack.toml

[phases.setup]
# Instala Caddy, PHP-FPM y las extensiones necesarias
nixPkgs = [
    "caddy",
    "php82",
    "php82-fpm", 
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql"
]
nixpkgsArchive = "aea547d4ec4ac01efe763cde7ccfbb263d5e2b86"

[phases.build]
# Instala las dependencias de Composer
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.start]
# Inicia PHP-FPM en segundo plano, y luego inicia Caddy en primer plano
cmd = "php-fpm -D && caddy run --config /app/Caddyfile --adapter caddyfile"